name: 'Frontend: PR'

on:
  pull_request:
    branches: ['*']

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Init NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.2'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
      - name: Init Thrift
        uses: valitydev/action-setup-thrift@v1.0.0
      - name: Install Packages
        run: npm ci
      - name: Build
        run: npm run codegen
